---
title: "Global Plastic Waste"
author: "Gareth Maddock"
date: "21/05/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

```

# Read in data

```{r read in data}
coast_vs_waste <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-21/coastal-population-vs-mismanaged-plastic.csv") %>% 
  janitor::clean_names()

mismanaged_vs_gdp <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-21/per-capita-mismanaged-plastic-waste-vs-gdp-per-capita.csv") %>% 
  janitor::clean_names()

waste_vs_gdp <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-21/per-capita-plastic-waste-vs-gdp-per-capita.csv") %>% 
  janitor::clean_names()
```

# Check `code` can be used to join tables together

Just validating that each code appears 3 times - which wouldn't be the case if there were typos. 

Only exceptions I have found are `TLS` (Timor) and `OWID_KOS` (Kosovo).

```{r test}

# Unique vector of codes for each dataset
test <-
list(coast_vs_waste, mismanaged_vs_gdp, waste_vs_gdp) %>% 
  lapply(function(dt) sort(unique(dt$code)))

# Put all 3 vectors into single vector, and count number of appearances
test <-
  do.call(c, test) %>% 
  table

# Show entries where frequency != 3 - should only be TLS and OWID_KOS
test[test != 3]

# Remove "test" from the global environment
rm(test)
```

# Aggregate Data into Single Table

```{r join}

aggregated_data <-
  list(coast_vs_waste, mismanaged_vs_gdp, waste_vs_gdp) %>% 
  map_dfr(~gather(., variable, value, -entity, -code, -year)) %>% 
  distinct() %>% 
  spread(variable, value)

```

